### ISSUE TITLE
გადაამოწმეთ მენიუ (ლოგო და ნავიგაცია) რამდენად სწორადაა ზომებში - ზემოდან დაშორება, გვერდიდან, მენიუს ელემენტების დაშორება ერთმანეთს შორის (ილუსტრატორში ნახეთ მთლიანი დიზაინის სიგანე და შემდეგ კონკრეტული სიგანე. შეფარდებით თქვენს ეკრანს მოარგეთ)

### ISSUE THREAD

**Issue by GiorgiMaziashvili** [GeoLabJuniors/fonts-website#10]

**Comment by AnanoAspanidze** [comment]
ყოჩაღ.
ზუსტი ზომები დასვი. თუმცა, ვიზუალურად ძალიან გავიდა და სიმაღლეები დავუპატარავე. დიზაინერი რამეს თუ იტყვის, მერე თვითონ შევცვლი ისევ. ეს დიზაინი 1920 პიქსელზეა აწყობილი (სიგანე) და ზოგიერთი ზომა თვალის ზომით შეგვიძლია, შევცვალოთ. როგორც ვიზუალურად უფრო კარგი იქნება. მერე თუ რამე არ მოეწონება, მე შევცვლი.
მენიუს კომპონენტებს შორის მანძილი შევამცირე. 70px იყო დიზაინში და პადინგები მოვუშალე ა ტაგებს.
