### ISSUE TITLE
დიზაინის ფაილში საბეჭდი მანქანა უფრო დიდ ადგილს იკავებს, მგონი შესასწორებელი გავქვს ან ფოტოს ზომა ან თვითონ კონტეინერის

### ISSUE THREAD

**Issue by GiorgiMaziashvili** [GeoLabJuniors/fonts-website#12]

**Comment by Perfstranger** [comment]
ძალიან კარგია ( :

**Comment by GiorgiMaziashvili** [comment]
მადლობა.

**Comment by AnanoAspanidze** [comment]
ვნახე, რომ ზომები დაამთხვიე და კარგი გიქნია, მაგრამ ახლა საბეჭდი მანქანა ძალიან დიდია. ამიტო, ახლა, ამ ეტაპზე იყოს დაახლოებით ისე, როგორც აქამდე და მერე ვნახოთ. შეიძლება, ავტომატურად ისე დავწეროთ, რო ნებისმიერ ეკრანზე ეს საბეჭდი მანქანა მთლიანად ჩანდეს. ამას მერე ვკითხავ კოკოს, სულ ბოლოს. ახლა შევეშვათ.
