### ISSUE TITLE
ისტორიის ნაწილი ილუსტრატორში - ზომები პიქსელებში რამდენად სწორადაა.

### ISSUE THREAD

**Issue by GiorgiMaziashvili** [GeoLabJuniors/fonts-website#13]

**Comment by AnanoAspanidze** [comment]
აქ რა ხდებოდა? 
იდეაში, კარგადაა ახლა დიდ ეკრანზე

**Comment by GiorgiMaziashvili** [comment]
წარწერა 20px არის მაკეტის მიხედვით

**Comment by AnanoAspanidze** [comment]
ჰო, კონტაქტის ტექსტიც 20 პიქსელია, მაგრამ ვიზუალურად ძალიან დიდი გამოდის. ამიტო, იყოს რაცაა ახლა და მერე თუ არ მოეწონება დიზაინერს, შეგვაცვლევინებს. 1920 პიქსელზეა დიზაინი აწყობილი და რაღაცეები შეგვიძლია, ჩვენით შევცვალოთ. ამ ყველაფერს დიზაინერს ვეტყვი, როცა ჩავაბარებთ პროექტს და თუ რამე შესაცვლელი იქნება, მე შევცვლი.

**Comment by GiorgiMaziashvili** [comment]
ok

2017-05-25 19:32 GMT+04:00 AnanoAspanidze <notifications@github.com>:
