### ISSUE TITLE
რესფონსივი: დიზაინერები&ხელმძღვანელები:ბლოკის დაშორება ზემოდან, სათაურის და ფოტოების დაშორება, ფონტის ზომები, თითოეული ბლოკის ბოლოს სამწერტილი(დიზაინშია) და კლიკზე დანარჩენი ხალხის ჩვენება. არ შეცვალო სხვადასხვა ეკრანზე გამოჩენილი ხალხის რაოდენობა.

### ISSUE THREAD

**Issue by AnanoAspanidze** [GeoLabJuniors/fonts-website#19]

**Comment by AnanoAspanidze** [comment]
მშვენიერია, ვიდეო ჩაგიწერე, როგორ უნდა გაკეთებულიყო პადინგების თემა. და რაც იქ დავწერე, ის 992 მედია ტაგში ჩავსვი (დიდ ეკრანზე პადინგი 15 მინდოდა და 992-მდე 10 და იმიტო).

**Comment by AnanoAspanidze** [comment]
ერთ პატარა ბაგი გვაქვს: 768 პიქსელიდან 991-ის ჩათვლით დიზაინერები ცუდად ჩანს: 3 ტიპი ჩანს და მეოთხე ქვემოთ ხტება, მაგრამ არაუშავს, დავიკიდოთ.

**Comment by Perfstranger** [comment]
ეგ ბაგი მეც შევამჩნიე მაგრამ ვერ გავიგე როგორ დამესვა ლამაზად :|
