### ISSUE TITLE
დიზაინერების და ხელმძღვანელების ნაწილის ზომების შემოწმება ილუსტრატორში - რამდენად ემთხვევა. ფოტოებს ჩარჩო არ უნდა. ჰოვერის ანიმაცია - რომ ახლოვდება, ეგეც გამოვრთოთ ამ ეტაპზე.

### ISSUE THREAD

**Issue by salomechukhua** [GeoLabJuniors/fonts-website#2]
დიზაინერების და ხელმძღვანელების ნაწილის ზომების შემოწმება ილუსტრატორში - რამდენად ემთხვევა. ფოტოებს ჩარჩო არ უნდა. ჰოვერის ანიმაცია - რომ ახლოვდება, ეგეც გამოვრთოთ ამ ეტაპზე.

**Comment by kote-d** [comment]
sorry gurl. ნაღდად იცი რო ეს გაასწორე? თუ კონიაკის ბრალია? :D

**Comment by AnanoAspanidze** [comment]
კარგი გოგო ხარ <3 ცოტა რამეები შევცვალე:
- დიზაინერების, ხელმძღვანელების, ისტორიის, კონტაქტის ქვეშ ქვესათაურებივით რომ არის, ისინი იტალიკი არ არის დიზაინში და წავუშალე ეს
- ყველა სათაურსა და ქვესათაურს შორის (მაგ: "დიზაინერები" არის სათაური, "და ფონტ-ინჟინრები.." არის ქვესათაური)  ილუსტრატორში დავხატე ოთხკუთხედი და გამოვიდა 16 პიქსელი. შევამცირე .title-ისთვის line-height და დავწერე 1
- დიზაინერების ფოტოს და სახელებს შორის 20 პიქსელი იყო და გავზარდე. იგივე ხელმძღვანელებშიც.
- ხელმძღვანელების სექციის დაშორება ზემოდან (დიზაინერების სექციიდან) უნდა ყოფილიყო 150 პიქსელი, დიზაინერების - 168. ხელმძღვანელების პადინგი ქვემოთ - 168 უნდა ყოფილიყო.

და ბოლოს: არაფერი მიქნია ფონტებისთვის. დიზაინში სხვა ზომებია, მაგრამ არ ეტევა სახელები და ან ასე დავტოვოთ, ან ფოტოებს შევამცირებ მერე, ბოლოს. კოკოს ვკითხავ.
