### ISSUE TITLE
დააპატარავეთ ის ტექსტი, საბეჭდ მანქანასთან რომაა. ძალიან დიდია ზოგ ეკრანზე. რესფონსივები დაგჭირდებათ - მედია ტაგები.

### ISSUE THREAD

**Issue by Perfstranger** [GeoLabJuniors/fonts-website#3]
დააპატარავეთ ის ტექსტი, საბეჭდ მანქანასთან რომაა. ძალიან დიდია ზოგ ეკრანზე. რესფონსივები დაგჭირდებათ - მედია ტაგები.

**Comment by AnanoAspanidze** [comment]
კარგი ხარ <3 ცოტა კიდე დავაპატარავე და სულ ბოლოს გადავუვლი და შევცვლი კიდე სავარაუდოდ.
