### ISSUE TITLE
კოტეს: სლაიდერი (რითიც დაპატარავება ხდება) ესე რო მუშაობდეს? ანუ თავზე რიცხვებიც რო ეწერებოდეს?

### ISSUE THREAD

**Issue by kote-d** [GeoLabJuniors/fonts-website#4]
https://cl.ly/3j1v1f0W0G2C

**Comment by kote-d** [comment]
@AnanoAspanidze რაღაცეები გავასწორე და ნახე და თუ რამეა გადასასწორებელი მითხარი. თუ არა და my work here is done ;)

**Comment by kote-d** [comment]
ესეც მზადაა(და მაინც რამდენს შვება ცოტა გრადუსი :P)

**Comment by Perfstranger** [comment]
შენ ყოფილხარ რაც ყოფილხარ 🙌🏻😂

**Comment by AnanoAspanidze** [comment]
<3
