### ISSUE TITLE
ლოგოსთან წარწერა რომ არის მარჯვნივ, იმას line-height გაუზარდეთ და ცოტა ქვემოთ ჩამოწიეთ - დიზაინის მიხედვით

### ISSUE THREAD

**Issue by Perfstranger** [GeoLabJuniors/fonts-website#5]

**Comment by AnanoAspanidze** [comment]
<3 კარგი გოგო ხარ.
წარწერას font-weight გავუზარდე, ცოტა რომ გამუქებულიყო. 
და ოდნავ უფრო მოვაშორე ლოგოს (ლოგოს მარჯვენა მარჯინი გავზარდე)
